# YOUR NAME OR TITLE OF YOUR SITE
name: Yaros Mallorca

# YOUR BRAND/PERSONAL TAGLINE
tagline: Professional Drone Pilot & Software Developer

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/YarosMallorca.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://www.yarosfpv.com/img/project-5.jpg

# SOCIAL MEDIA
links:
  # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: profile.php?id=61551663110660
    Color: "#3b5998"
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: yaros_mallorca
    Color: "#DD2A7B"
    Icon-Class: fab fa-instagram

    # THREADS.NET
  - Name: Threads
    URL: https://threads.net
    Username: yaros_mallorca
    Color: "#000000"
    Icon-Class: fa-brands fa-threads
    Text_Color: "#ffffff"

    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: yaroslav-syubayev-659152291
    Color: "#2867B2"
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/@
    Username: YarosMallorca
    Color: "#ff0000"
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: YarosMallorca
    Color: "#6e5494"
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: "mailto:contact@yarosfpv.com"
    Icon-Class: fas fa-envelope
    Color: "#e17055"
    Text_Color: "#ffffff"

  # TWITCH
  - Name: Twitch
    URL: "https://twitch.tv"
    Username: yarosmallorca
    Icon-Class: fab fa-twitch
    Color: "#9147fe"
    Text_Color: "#ffffff"

    # WHATSAPP
  - Name: WhatsApp
    URL: https://wa.me
    Username: "+34610317175"
    Color: "#25d366"
    Icon-Class: fab fa-whatsapp

  # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: YarosMallorca
    Color: "#0088cc"
    Icon-Class: fab fa-telegram-plane

    # SNAPCHAT
  - Name: Snapchat
    URL: https://www.snapchat.com/add
    Username: "yarossyubayev"
    Color: "#FFFC00"
    Text_Color: "#000000"
    Icon-Class: fab fa-snapchat-ghost

    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id
    Username: "yarosmallorca"
    Color: "#66c0f4"
    Text_Color: "#000000"
    Icon-Class: fab fa-steam

    # DISCORD
  - Name: Discord
    URL: "https://discord.gg"
    Username: yarossyubayev
    Icon-Class: fab fa-discord
    Color: "#5865F2"
    Text_Color: "#ffffff"

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: ajisn08w99jcr8d4xqv2ezssu
    Color: "#1DB954"
    Icon-Class:
      fab fa-spotify

      # TIKTOK
  - Name: TikTok
    URL: https://www.tiktok.com
    Username: yarosmallorca
    Color: "#FE2C55"
    Icon-Class: fab fa-tiktok

footer: "Yes"

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /

# Default Markdown Engine
markdown: kramdown
